

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true


[tool.pylsp]
plugins.jedi_completion.enabled = true
plugins.jedi_signature_help.enabled = true
plugins.jedi_hover.enabled = false
plugins.pylsp_mypy.enabled = true


[tool.mypy]
plugins = [ "mypy_django_plugin.main" ]
check_untyped_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
strict = true
files = "**/*.py"



[tool.pycodestyle]
ignore = ["E303"]

[tool.django-stubs]
django_settings_module = "myproject.settings"

