# Generated by Django 5.1.7 on 2025-03-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("GBP", "GBP"), ("USD", "USD"), ("EUR", "EUR")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(blank=True, max_length=1, null=True, unique=True),
        ),
    ]
