# Generated by Django 5.1.7 on 2025-03-18 17:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_currency_alter_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('750.00'), max_digits=50),
        ),
    ]
