# Generated by Django 5.1.7 on 2025-04-09 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                decimal_places=20, default=Decimal("750.00"), max_digits=68
            ),
        ),
    ]
