# Generated by Django 5.1.7 on 2025-03-16 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=19, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["sender", "receiver", "date"],
                name="payapp_tran_sender__a58f98_idx",
            ),
        ),
    ]
