# Generated by Django 5.1.7 on 2025-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
