# Generated by Django 5.1.7 on 2025-04-08 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0008_alter_request_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="id",
        ),
        migrations.AddField(
            model_name="request",
            name="payment_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="payapp.payment",
            ),
            preserve_default=False,
        ),
    ]
