# Generated by Django 5.1.7 on 2025-04-08 23:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0009_remove_request_id_request_payment_ptr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="payment_ptr",
        ),
        migrations.AddField(
            model_name="request",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=750, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 4, 8, 23, 33, 32, 867255),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request_sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_sender",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
