# Generated by Django 5.1.7 on 2025-04-09 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0010_remove_request_payment_ptr_request_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="fee",
        ),
        migrations.RemoveField(
            model_name="request",
            name="fee",
        ),
    ]
