# Generated by Django 5.1.7 on 2025-04-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0011_remove_payment_fee_remove_request_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="receiver_amount",
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="rate",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
