# Generated by Django 5.1.7 on 2025-04-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0012_request_receiver_amount_alter_payment_rate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="receiver_amount",
            new_name="sender_amount",
        ),
    ]
