# Generated by Django 5.1.7 on 2025-04-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0014_payment_receiver_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="request",
            name="amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="sender_amount",
            field=models.DecimalField(decimal_places=20, default=1, max_digits=68),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="receiver_amount",
            field=models.DecimalField(decimal_places=20, default=1, max_digits=68),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="payment",
            name="rate",
            field=models.DecimalField(decimal_places=20, max_digits=68),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receiver_amount",
            field=models.DecimalField(decimal_places=20, default=1, max_digits=68),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="request",
            name="rate",
            field=models.DecimalField(decimal_places=20, max_digits=68),
        ),
        migrations.AlterField(
            model_name="request",
            name="sender_amount",
            field=models.DecimalField(decimal_places=20, default=1, max_digits=68),
            preserve_default=False,
        ),
    ]
