# Generated by Django 5.1.7 on 2025-04-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0015_remove_payment_amount_remove_request_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("U", "Unread"), ("R", "Read")],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "n_type",
                    models.CharField(
                        choices=[("U", "Unread"), ("R", "Read")], max_length=1
                    ),
                ),
                ("message", models.CharField(max_length=200)),
                (
                    "paymnet_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_id",
                        to="payapp.payment",
                    ),
                ),
                (
                    "request_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_id",
                        to="payapp.request",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
