# Generated by Django 5.1.7 on 2025-04-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0017_alter_notification_options_notification_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="from_request",
            field=models.BooleanField(default=False),
        ),
    ]
