# Generated by Django 5.1.7 on 2025-04-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0018_payment_from_request"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="paymnet_id",
            new_name="paymnet",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="request_id",
            new_name="request",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="user_id",
            new_name="user",
        ),
    ]
