# Generated by Django 5.1.7 on 2025-04-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0019_rename_paymnet_id_notification_paymnet_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="paymnet",
            new_name="payment",
        ),
    ]
